language: node_js
node_js:
  - '8'
script:
  - set -e
  - npm run linter
  - npm run build
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - npm config set git-tag-version=false
  - NPM_VERSION=$(npm version patch)
  - git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
  - git remote remove origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/11joselu/template-hint.git
  - git push origin HEAD:master
deploy:
  edge: true
  provider: npm
  email: joselu11cabrera@gmail.com
  api_key: '$NPM_API_TOKEN'
